name: project
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - open-clip-torch
  - plyfile
  - python
  - pip
  - pytorch=2.3
  - pytorch-cuda=11.8
  - torchaudio
  - torchvision
  - tqdm
  - opencv
  - tensorboard
  - jaxtyping
  - matplotlib
  - typing
  - pathlib
  - pip:
    - submodules/segment-anything-langsplat
    - submodules/langsplat-rasterization
    - submodules/simple-knn
